### ISSUE TITLE
Allow mods to access Twitch username lookup features on broken reports

### ISSUE THREAD

**Issue by deadroxy** [AnyKeyOrg/anykey#41]

**Comment by wninohira** [comment]
I made some wireframes/designs for the feature. I am planning to work on implementing it but let me know if I should change anything!

**- Default view**
![image](https://user-images.githubusercontent.com/44479569/181123428-a9672b78-6ba9-49d9-a3ea-7f2b3a0a3888.png)

**- When the typed username is found on twitch and Anykey's record**
![image](https://user-images.githubusercontent.com/44479569/181123461-924505fe-248a-4bb8-9a62-ee49803c58dd.png)

**- When the user did not sign pledge**
![image](https://user-images.githubusercontent.com/44479569/181123509-a15ff046-2198-4b4f-aaaa-6cf08beef547.png)

**- When the user does not exist**
![image](https://user-images.githubusercontent.com/44479569/181123532-08b27122-4a5e-42e6-b62b-4a00a3fc1a7e.png)

**Comment by deadroxy** [comment]
Shout out to @wninohira for this great start. Ended up going with a different set of features to address this overall goal in PR #61, but this is a good idea to review if those don't meet the ComfyCrew's needs.
