### ISSUE TITLE
Upgrade Redis version on Heroku

### ISSUE THREAD

**Issue by deadroxy** [AnyKeyOrg/anykey#44]
Heroku is deprecating our current version of Redis on 6/30/2021. It will run fine until we try to push code to production, so we should be proactive about making this upgrade.

<img width="572" alt="Heroku Email (2021-4-2)" src="https://user-images.githubusercontent.com/126442/113660035-45b6a280-9671-11eb-96d0-16ab0887633f.png">

**Comment by epartakki** [comment]
It looks like there were some forced upgrades in June of 2021: https://devcenter.heroku.com/articles/heroku-redis-hobby-deprecation

I tried to test an upgrade, but I do not have the correct credentials. It looks like the current AnyKey version is: 7.42.5

**Comment by deadroxy** [comment]
Indeed, upgrading the services in production requires admin credentials :D But this story is a bit stale because I have upgrade Redis once (or twice?) since I put this here, but didn't actually change the minimum version in our Gemfile :]

**Comment by epartakki** [comment]
Got it! Thank you for explaining! :D
