### ISSUE TITLE
Allow mods comment on reports

### ISSUE THREAD

**Issue by wninohira** [AnyKeyOrg/anykey#50]
- [x] General commenting
  - Show icon next to report with comments in report index view
  - allow mods to leave a comment on staff show page
  - Allow mods to see previous comment on staff show page
- [ ] Send notification on anykey discord when comment is made (#49)
- [ ] Allow mods reply to specific comment (and mention the commenter in discord bot message)

**Comment by deadroxy** [comment]
Great work by @wninohira getting this started. Closed with PR #61.
